### PR TITLE
cuck, simp, soyboy

### PR DESCRIPTION
**Pull request by Nezteb**
A few words from 2020/2021 that have risen in infamy on some online platforms (like Twitch).

### CODE REVIEW

**Comment by Bixilon** [comment]
Why should simp be a bad word?

**Comment by PaulDotSH** [comment]
Why are they profane?

**Comment by PaulDotSH** [comment]
It's like saying "add big head", since it can be used as an insult

**Comment by Nezteb** [comment]
If y'all think these words aren't profane but `nipple`, `penis`, `pubic`, `puke`, `shag`, `steamy`, and so on are, then what's the point of this repo? It collects all kinds of words that some people (not necessarily either of you) see as profane, bad, insulting, raunchy, etc.

Granted, neither of you are actual contributors to this repo, but it's been a year and this hasn't been looked at by anyone else so I might as well close it.

**Pull request merged**
